#spring.application.name=task-manager
#
#spring.h2.console.enabled=true
#spring.datasource.generate-unique-name=false
#spring.datasource.name=taskManager

spring.sql.init.mode=always
file.upload-dir-img=./uploads/images
spring.web.resources.static-locations=file:./uploads/images/